server:
#    tomcat:
#        max-threads: 1000
#        min-spare-threads: 30
  port: 8888
spring:
  application:
    name: gateway-zuul

#默认情况下，Zuul会代理所有注册到Eureka Server的微服务，
#并且Zuul的路由规则如下：http://ZUUL_HOST:ZUUL_PORT/微服务在Eureka上的serviceId/**  会被转发到serviceId对应的微服务
#配置方法一
# 当 zuul 不配合 Eureka 服务发现服务的时候，Zuul 的路由就要基于 URL 去路由
#zuul:
#  routes:
#    mall-admin:
#      path: /mall-admin/**
#      url: http://localhost:8080/mall-admin
#    mall-portal:
#      path: /mall-portal/**
#      serviceId: mall-portal
#      stripPrefix: false
#配置方法二
## 如果只配置path，不配置serviceId。则customName相当于服务名称。
## 符合path的请求路径直接路由到customName对应的服务上。
zuul:
  routes:
    mall-admin:
      path: /mall-admin/**
      stripPrefix: false
#    mall-portal:
#      path: /mall-portal/**
#      serviceId: mall-portal
#      stripPrefix: false
    mall-portal: /**
#  如果没有设置servlet.context-path: /mall-portal  可以写成 zuul。routes。mall-portal: /**
#当stripPrefix=true的时候 （http://127.0.0.1:3333/api/user/list -> http://192.168.1.100:8080/user/list）
#当stripPrefix=false的时候（http://127.0.0.1:5555/api/user/list -> http://192.168.1.100:8080/api/user/list）
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka #告诉服务提供者要把服务注册到哪儿
  instance:
    prefer-ip-address: true #显示客户端真实ip

