server:
  session-timeout: 1800
#    tomcat:
#        max-threads: 1000
#        min-spare-threads: 30
  port: 8090
#  servlet:
#    context-path: /mall-portal
#    uri-encoding: utf-8
#security:
#  basic:
#    enabled: false
spring:
  application:
    name: mall-portal #不要使用下划线
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: dev
  servlet:
    multipart:
      max-file-size: 30
      max-request-size: 30
  cache:
    type: ehcache
    ehcache:
      config: classpath:config/ehcache.xml

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*Mapper.xml
  typeAliasesPackage: com.gwen.**.dao
#[弃用]配置缓存和session存储方式，默认ehcache,可选redis,[弃用]调整至 spring cache type【shiro.用户，权限，session，spring.cache通用】
#[弃用]cacheType: ehcache
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka #告诉服务提供者要把服务注册到哪儿
  instance:
    prefer-ip-address: true #显示客户端真实ip
feign:
  hystrix:
    enabled: true